// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxcrzmztyvtsmvrvdbyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Y3J6bXp0eXZ0c212cnZkYnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDg4NzEsImV4cCI6MjA2NTg4NDg3MX0.nqQIEpL4OLnq0M0HmtemKa4f3sug6KBHmw0NPut5QKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);